Created Intake Roller Subsystem in Comp 2024
usfirst-frc-2135/robot2024 pull request #19
Opened 2024-02-03 19:40 UTC by nishka-sethi

2024-02-04 02:05 UTC, hpark-24 approved these changes, later dismissed
Overall it looks good! We might change the controls later on, but nice job today!

2024-02-04 02:05 UTC, hpark-24 commented on Comp2024/src/main/java/frc/robot/RobotContainer.java
> +    m_operatorPad.leftBumper( ).onTrue(new Dummy("oper right bumper"));
It's a small thing, but make sure this Dummy says "left bumper" since it is on the left (not the right)!

2024-02-04 02:05 UTC, hpark-24 commented on Comp2024/src/main/java/frc/robot/RobotContainer.java
> +    m_operatorPad.leftTrigger(Constants.kTriggerThreshold).onTrue(new Dummy("oper right trigger"));
The same with this where I think this should be: Dummy("oper left trigger"), instead of "right."

2024-02-04 03:48 UTC, jmullins16 requested changes
Minor changes, but close to ready to merge. Let's get them done, so we can do it.

2024-02-04 03:48 UTC, jmullins16 commented on Comp2024/src/main/java/frc/robot/generated/TunerConstants.java
> -  private static final double                       kFrontLeftEncoderOffset  = 0.414306640625;
Not sure why these changes came in on your PR. I thought they would be on Hannah's branch. It's OK, but surprised me.

2024-02-05 07:08 UTC, jmullins16 approved these changes
Ready to go!

2024-02-05 07:08 UTC, merged