Created Trajectory to Pathplanner Trajectory Method + Debugged Auto
usfirst-frc-2135/robot2024 pull request #4
Opened 2024-01-16 23:59 UTC by hpark-24

2024-01-17 02:15 UTC, ananyakidambi reviewed
Looks Good

2024-01-17 02:19 UTC, zaraansari17 approved these changes, later dismissed
looks good

2024-01-17 23:04 UTC, grace-mills submitted a review, later dismissed
looks good

2024-01-18 00:03 UTC, jmullins16 commented
force comments

2024-01-18 01:09 UTC, jmullins16 commented
Trying to force comments to show.

2024-01-18 01:30 UTC, jmullins16 commented on Comp2023-Imported/src/main/java/frc/robot/subsystems/Swerve.java
> +    return (m_trajTimer.hasElapsed(m_trajectory.getTotalTimeSeconds( ) + 0.120)); // TODO: Give more time if the robot needs to adjust more
Why would we keep this TODO comment? Doesn't seem very useful and is quite obvious that we need to test.

2024-01-18 01:30 UTC, jmullins16 commented on Comp2023-Imported/src/main/java/frc/robot/subsystems/Swerve.java
> +    else
We should ONLY be updating the odometry within the periodic method and no where else. Please explain (functionally) why this "else" block has been inserted. Did we copy it from other code?

2024-01-18 01:30 UTC, jmullins16 commented on Comp2023-Imported/src/main/java/frc/robot/subsystems/Swerve.java
> +
What is this TODO supposed to add (functionally)?

2024-01-18 01:30 UTC, jmullins16 commented on Comp2023-Imported/src/main/java/frc/robot/subsystems/Swerve.java
> +  private List<Trajectory.State>   trajStates          = new ArrayList<Trajectory.State>( );
This is a class member variable is named incorrectly. OR it really should be a local variable in the pathPlannerTrajectoryToTrajectory method, since it is returned to the caller.

2024-01-18 01:30 UTC, jmullins16 commented on Comp2023-Imported/src/main/java/frc/robot/subsystems/Swerve.java
> +    Trajectory newTrajectory = new Trajectory(trajStates);
Why not just "return new Trajectory(trajStates)" instead of creating a superfluous variable "newTrajectory" to return?

2024-01-18 01:30 UTC, jmullins16 commented on Comp2023-Imported/src/main/java/frc/robot/subsystems/Swerve.java
> +    Trajectory.State newTrajectoryState =
Another example where I think we could just return the Rvalue (right side of the equals sign) instead of creating a local variable "newTrajectoryState".

2024-01-18 01:30 UTC, jmullins16 commented on Comp2023-Imported/src/main/java/frc/robot/commands/AutoDrivePath.java
> +    m_useInitialPose = false;//useInitialPose;
Why is this set to false? Is it temporary (since it's still in the comment)?

2024-01-18 01:30 UTC, jmullins16 commented on Comp2023-Imported/src/main/java/frc/robot/Constants.java
> +      AUTOEXAMPLE
If this stays, can we call it a "test path" instead of "example". It's a little more related to what it is doing.

2024-01-18 01:30 UTC, jmullins16 commented on Comp2023-Imported/src/main/java/frc/robot/subsystems/Swerve.java
> +    Trajectory.State newTrajectoryState =
try again

2024-01-20 04:27 UTC, jmullins16 requested changes
Let's review tomorrow together. Logic looks great. Just want to resolve the minor questions.

2024-01-20 04:27 UTC, jmullins16 commented on Comp2023-Imported/src/main/java/frc/robot/commands/AutoDrivePath.java
> +    m_swerve.driveWithPathFollowerExecute(m_useInitialPose);
I'm not sure what the initial pose has to do while we're executing a path follower. The check should only be when the path is initialized, right? Let's review what this is doing and where it came from.

2024-01-20 04:27 UTC, jmullins16 commented on Comp2023-Imported/src/main/java/frc/robot/commands/DriveLimelightPath.java
> +      m_swerve.driveWithPathFollowerExecute(true); //Sets Path to not check for current position
While comments can be useful, I think that intellisense will display what that variable name is with "true" beside it. See what you think.

2024-01-20 04:27 UTC, jmullins16 commented on Comp2023-Imported/src/main/java/frc/robot/subsystems/Swerve.java
> +  public Trajectory PPTrajtoWPITraj(PathPlannerTrajectory trajectory)
I realize I said to shorten the name, but "Traj" is probably a little too far. If it was a local variable (used within a method), then more cryptic names are OK. But a public method nameshould be more complete. PPTrajectoryToWPITrajectory is OK without the full PathPlanner name.

2024-01-20 04:27 UTC, jmullins16 commented on Comp2023-Imported/src/main/java/frc/robot/subsystems/Swerve.java
> +      resetOdometry(m_poseEstimator.getEstimatedPosition( ));
Let's review this. If we're going to reset our pose to the initial pose in the path, that's the first case. If we aren't, then we're using the existing robot pose--which "is what it is". I think we're resetting the odometry with the current position of the odometry.

2024-01-20 04:27 UTC, jmullins16 commented on Comp2023-Imported/src/main/java/frc/robot/subsystems/Swerve.java
> +    //
Not sure what the //s are adding here.

2024-01-21 04:27 UTC, jmullins16 requested changes
Path stuff all looks good. Clean up the incorrect comments in the subsystems and I'll approve, but I really like your empty templates for those mechanisms! Nice work!

2024-01-21 04:27 UTC, jmullins16 commented on Comp2024/src/main/java/frc/robot/subsystems/Climber.java
> +// Intake Subystem - takes in Notes and delivers them to the Shooter
Check your comments: "Intake"?

2024-01-21 04:27 UTC, jmullins16 commented on Comp2024/src/main/java/frc/robot/subsystems/Climber.java
> +// Intake subsystem class
Ditto

2024-01-21 04:27 UTC, jmullins16 commented on Comp2024/src/main/java/frc/robot/subsystems/Climber.java
> +  private final TalonFX m_climberL = new TalonFX(0);
We'll need to grab the CANID constants from Zara as the next step, but this is OK to get this checked in.

2024-01-21 04:27 UTC, jmullins16 commented on Comp2024/src/main/java/frc/robot/subsystems/Feeder.java
> +// Intake Subystem - takes in Notes and delivers them to the Shooter
Comments...

2024-01-21 04:27 UTC, jmullins16 commented on Comp2024/src/main/java/frc/robot/subsystems/Feeder.java
> +// Intake subsystem class
Ditto

2024-01-21 04:27 UTC, jmullins16 commented on Comp2024/src/main/java/frc/robot/subsystems/Feeder.java
> +  private final WPI_TalonSRX m_feeder       = new WPI_TalonSRX(0);
My estimate is:
- feeder roller
- feeder rotary
- MAYBE a CANCoder
- Limit switch for detecting a note acquired
- Limit switch for zeroing rotary mechanism IF no CANCoder

2024-01-21 04:27 UTC, jmullins16 commented on Comp2024/src/main/java/frc/robot/subsystems/Intake.java
> +  private final WPI_TalonSRX m_intakeRoller       = new WPI_TalonSRX(0);
See comments on feeder mechanism

2024-01-21 04:27 UTC, jmullins16 commented on Comp2024/src/main/java/frc/robot/subsystems/Shooter.java
> +// Intake Subystem - takes in Notes and delivers them to the Shooter
Comments...

2024-01-21 04:27 UTC, jmullins16 commented on Comp2024/src/main/java/frc/robot/subsystems/Shooter.java
> +// Intake subsystem class
Ditto

2024-01-21 19:46 UTC, zaraansari17 submitted a review, later dismissed
Looks good

2024-01-21 20:16 UTC, grace-mills approved these changes, later dismissed
looks right

2024-01-21 21:59 UTC, jmullins16 approved these changes
Looks good!

2024-01-21 21:59 UTC, merged