Prototype code (conversion errors)
usfirst-frc-2135/robot2024 pull request #9
Opened 2024-01-21 00:29 UTC by ananyakidambi

2024-01-21 04:38 UTC, jmullins16 requested changes
Glad you got this checked in. 
1) Please merge from main back into your branch. This should eliminate simgui*.json files from being tracked for changes, and the auto-formatter should be enabled.
2) It is difficult to review your changes, because the entire ExampleSmartMotorController.java file (all lines) as changed. I know this isn't true, because see many lines are the same. I suspect this might be because you're on WIndows (which can change the line endings on EVERY line if incorrectly configured). We'll look at this more closely next time your in.

2024-01-21 23:39 UTC, grace-mills commented on Comp2023-Imported/src/main/java/frc/robot/subsystems/Swerve.java
This needs to be set to true to allow limelight to work and recognize aprilTags. If it is effecting your motor controller maybe there is a work around

2024-01-21 23:40 UTC, grace-mills commented on Comp2023-Imported/src/main/java/frc/robot/subsystems/Swerve.java
>    private void updateSmartDashboard( )
These are also SmartDashboard outputs that give the robots estimated position and are used with limelight

2024-01-22 00:11 UTC, hpark-24 requested changes
It looks like a lot of code is being deleted here that I don't think you meant to delete (i.e. poseEstimation in Comp2023-Imported). Could you please make sure that only your changes are in this pull request?

2024-01-22 04:55 UTC, jmullins16 requested changes
It appears that your branch has been corrupted a bit. Looks like it has deleted lots of files that should not have been affected in other projects. We need to recover just your changes and do this again before merging.

2024-01-24 23:53 UTC, closed without merging